quizsite/quizcreator/urls.py
# Dylan O'Connell Quizsite. This stores all the URLs related to quizzes. Imported by quizsite/URLs.py

from django.conf.urls import include, url
from quizsite import views

urlpatterns = [
    url(r'^$', views.quizzes, name='quizzes'),
    url(r'^listquizresults$', views.listquizresults, name='listquizresults'),
    url(r'^(?P<quiz_id>[0-9]+)/(?P<question_id>[0-9]+)/$', views.question, name='question'),
    url(r'^addquestion$', views.addquestion, name='addquestion'),
    url(r'^(?P<quiz_id>[0-9]+)/beginquiz$', views.beginquiz, name='beginquiz'),
    url(r'^(?P<quiz_id>[0-9]+)/endofquiz$', views.endofquiz, name='endofquiz'),
    url(r'^(?P<quiz_id>[0-9]+)/finishquiz$', views.finishquiz, name='finishquiz'),
    url(r'^(?P<quiz_id>[0-9]+)/checkresults$', views.checkresults, name='checkresults'),
    url(r'^(?P<quiz_id>[0-9]+)/(?P<username>\w+)/quizresults$', views.quizresults, name='quizresults'),
    url(r'^addanswer$', views.addanswer, name='addanswer'),
    url(r'^addquiz$', views.addquiz, name='addquiz'),
    url(r'^(?P<quiz_id>[0-9]+)/(?P<question_id>[0-9]+)/submitanswer$', views.submitanswer, name='submitanswer'),
    url(r'^bugreport$', views.bugreport, name='bugreport'),
    url(r'^viewbugreports$', views.viewbugreports, name='viewbugreports'),
]

quizsite/quizsite/urls.py
from django.conf.urls import include, url
from quizsite import views
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.home, name="home"),
    # More info on what the below includes is described here
    # https://docs.djangoproject.com/en/1.8/topics/auth/default/#module-django.contrib.auth.views
    url(r'', include('django.contrib.auth.urls')),
    url(r'^quizzes/', include('quizcreator.urls', namespace="quizzes", app_name='quizcreator')),
    url(r'^account/', include('quizsite.account_urls', namespace="account", app_name='account')),
]

quizsite/quizcreator/models.py
# These are the models for our Django objects/SQL database.
# The readme has some high level info on how these interact. The docstrings 
# and comments have further details. The naming is intended to be intuitive,
# and understandable to a viewer of the code.
from django.db import models
from django.contrib.auth.models import User


# Our site stores quizzes, which have a name, and are referenced through a m2m relationship with questions.
class Quiz(models.Model):
    """Each Quiz has a name, and a m2m relationship with questions"""
    name = models.CharField(max_length=200, null=True)
    # We allow a m2m relationship between quizzes and questions because as the quizsite grows, it makes sense
    # for instructors to be able to reuse particularly good questions. This helps ensure that we do not repeat ourselves.
    questions = models.ManyToManyField('Question', through='QuestionOrdering')

    def __str__(self):
        """This determines the display name of our quiz"""
        if self.name:
            return self.name
        else:
            return '{} {}'.format('Quiz #:', self.id)


# Questions are what users have to answer, and are referenced by many answers, and have a m2m relationship
# with Quizzes. They have 'text' which is the question itself.
class Question(models.Model):
    """Each question is connected to quiz by m2m, is referenced by many answers, and has its own text"""
    text = models.CharField(max_length=200)

    def __str__(self):
        """The proper display name for the Question""" 
        return '{} {}'.format('Question #:', self.id)

#Due to the m2m relationship of quizzes and questions, we must have something that tracks 
# the ordering of each question for each quiz it is in. Thus, we use the through table,
# with ordering storing that data.
class QuestionOrdering(models.Model):
    """
    quiz and question have m2m relation with through table. QuestionOrdering allows us to track
    the ordering of the questions in each quiz.
    """
    quiz = models.ForeignKey(Quiz)
    question = models.ForeignKey(Question)
    ordering = models.PositiveIntegerField()


class Answer(models.Model):
    """ Each answer references a question, and has its own text, and whether it is correct"""
    text = models.CharField(max_length=200)
# An answer can either be fully correct, partly wrong, or fully wrong, and we store which of these 3 possibilities is the answer
# See the readme.txt for scoring details.
    correct = 'COR'
    partly_wrong = 'PART_W'
    fully_wrong = 'FULL_W'
    answer_choices = (
        (correct, 'Correct'),
        (partly_wrong, 'Partly Wrong'),
        (fully_wrong, 'Fully Wrong'),
    )
    correct_type = models.CharField(max_length=6, choices=answer_choices, default=fully_wrong)
    question = models.ForeignKey(Question, null=True, blank=True)

    def __str__(self):
        """It is displayed as just its text"""
        return self.text


# This is created when a user starts a quiz. When they submit the quiz, finished is set to True.
# When a superuser views the quizresult, the score is computed and stored.
class QuizResult(models.Model):
    """Each user attempt at a quiz is stored in a QuizResult. It stores user, quiz, whether it is finished, and the score"""
    # The score is initially 0. The score is only updated when a superuser views the results for that quiz, and is 
    # not meaningful before then.
    score = models.IntegerField(default=0)
    user = models.ForeignKey(User)
    quiz = models.ForeignKey(Quiz)
    finished = models.BooleanField(default=False)


# The user's responses to a quiz are stored as answer results. For every possible answer in a quiz, 
# we store an AnswerResult object that stores whether or not he selected it (in 'selected')
class AnswerResult(models.Model):
    """
    Users submit answers with an AnswerResult per answer that stores the user, the quiz, the question, the answer, and whether or
    not they did select that answer.
    """
    quiz = models.ForeignKey(Quiz)
    question = models.ForeignKey(Question)
    answer = models.ForeignKey(Answer)
    user = models.ForeignKey(User, null=True, blank=True)
    selected = models.BooleanField()


class BugReport(models.Model):
    """Users submit bug reports which store the user, the text of the report, and the timestamp of submission"""
    user = models.ForeignKey(User)
    report = models.CharField(max_length=1000, verbose_name="Bug Report")
    timestamp = models.DateTimeField(null=True)

quizsite/quizsite/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.template import loader
from datetime import datetime
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .forms import AddQuestionForm, AddAnswerForm, AddQuizForm, QuizResultForm, AnswerResultForm, BugReportForm
from django.forms import modelformset_factory
from quizcreator.models import Quiz, Question, Answer, QuestionOrdering, QuizResult, AnswerResult, BugReport
from django.db.models import Max
from django.contrib.auth import login, logout


# This is our basic homepage. For now, provides links to other pages.
def home(request):
    """Returns the home page of the website."""
    return render(request, 'quizsite/home.html')

# Provides a destination for login_view, and redirects to the Django login page. 
def login_view(request):
    """Returns our basic login page"""
    return redirect('/login')

# Logs out a user using django.contrib.auth, and redirects to home
def logout_view(request):
    """Returns our basic logout page"""
    logout(request)
    return redirect('/')


# View for the overall list of quizzes. Each quiz id is shown, and provides a link to the first question of that quiz
def quizzes(request):
    """Returns the page with a list of available quizzes."""
    quizzes_list = Quiz.objects.all()
    context = {
        'quizzes_list': quizzes_list,
    }
    return render(request, 'quizsite/quizzes.html', context)

# For a given quiz, allows the user to begin a quiz attempt
def beginquiz(request, quiz_id):
    """Returns a page which allows the user to begin a quiz
    
    If it receives a post request, it creates a QuizResult object.
    Otherwise, it provides a form to create a QuizResult object.
    """
    if request.method == "POST":
        # Only logged in users can begin a quiz
        if request.user.is_authenticated():
            quiz = get_object_or_404(Quiz, pk=quiz_id)
            quizresultform = QuizResultForm(request.POST)
            if quizresultform.is_valid():
                # Do not let a user begin a quiz they've already started.
                if QuizResult.objects.filter(quiz=quiz, user=request.user):
                    context = {'error': "You've already begun that quiz.", 'quiz': quiz}
                    return render(request, 'quizsite/alreadybegunquiz.html', context)
                # Otherwise, we save this QuizResult, and begin the quiz.
                else:
                    # Check that the submitted form has not had its values tampered with.
                    if quizresultform.cleaned_data['quiz'] == quiz and quizresultform.cleaned_data['user'] == request.user:
                        quizresultform.save()  
                        return redirect('/quizzes/{}/{}'.format(quiz_id, quiz.questions.all().first().id))
                    else:
                        context = {'error': "Invalid Submission."}
                        return render(request, 'quizsite/error.html', context)
            else:
                context = {'error': "Invalid Submission."}
                return render(request, 'quizsite/error.html', context)
        else:
            context = {'error': "You must be logged in to begin a quiz."}
            return render(request, 'quizsite/error.html', context)

    else:
        # If not POST, we display the QuizResult form to begin a quiz.
        quiz = get_object_or_404(Quiz, pk=quiz_id)
        user = request.user
        # We provide the initial data for the QuizResult form.
        quizresultform = QuizResultForm(initial={'quiz': quiz, 'user': user, 'finished': False})
        context = {
                'quiz': quiz,
                'quizresultform': quizresultform,
                }
        return render(request, 'quizsite/beginquiz.html', context)

# After submitting the final answer, this view allows the user to choose 
# whether to submit the quiz attempt, or to return to the quiz
def endofquiz(request, quiz_id):
    """ Gives the user the option submit quiz, or go back to start"""
    if request.user.is_authenticated():
        quiz = get_object_or_404(Quiz, pk=quiz_id)
        # We find the first question in the quiz, if available
        try:
            first_question = quiz.questions.all().first()
        except:
            first_question = None
        context = {'quiz': quiz, 'first_question': first_question}
        return render(request, 'quizsite/endofquiz.html', context)
    else:
        context = {'error': "Must be logged in to end a quiz."}
        return render(request, 'quizsite/error.html', context)


def finishquiz(request, quiz_id):
    """For a given quiz, attempts to submit the current users answers.

    This checks if the user has submitted an AnswerResult for each question on the quiz.
    If they have, it sets QuizResult.finished to True. It does not yet score the quiz.
    """
    # Only logged in users can submit a quiz
    if request.user.is_authenticated():
        quiz = get_object_or_404(Quiz, pk=quiz_id)
        # Check that the user has started the quiz, display error if not.
        if QuizResult.objects.filter(quiz=quiz, user=request.user):
            # Doublecheck that there are not two QuizResults in the system. This should be impossible, but we check anyways.
            if len(QuizResult.objects.filter(quiz=quiz, user=request.user)) == 1:
                # Check if they have completed the quiz
                if QuizResult.objects.filter(quiz=quiz, user=request.user).first().finished:
                    context = {'error': "You have already completed this quiz."}
                    return render(request, 'quizsite/error.html', context)
                # If there is a single, valid, unfinished quiz attempt, we verify that there is one answerresult for each answer
                else:
                    quizresult = QuizResult.objects.filter(quiz=quiz, user=request.user).first()
                    question_list = Question.objects.filter(quiz__id=quiz_id)
                    #For each answer, check that there is an answer result. Otherwise, display what answer is missing.
                    for question in question_list:
                        answer_list = question.answer_set.all()
                        for answer in answer_list:
                            try:
                                result = AnswerResult.objects.get(user=request.user, quiz=quiz, question=question, answer=answer)
                            except:
                                context = {'error': "There is not exactly one submitted answer for Quiz: {}, Question: {}. Answer: {}".format(quiz, question, answer)}
                                return render(request, 'quizsite/error.html', context)
                    # If the answers are all there, finish the quiz.
                    quizresult.finished = True
                    quizresult.save()
                    context = {'quiz': quiz}
                    return render(request, 'quizsite/submittedquiz.html', context)
            else:
                context = {'error': "There is an error, more than one quiz attempt active. Contact an administrator."}
                return render(request, 'quizsite/error.html', context)

        else:
            context = {'error': "You have not yet begun this quiz."}
            return render(request, 'quizsite/error.html', context)
    else:
        context = {'error': "Must be logged in to end a quiz."}
        return render(request, 'quizsite/error.html', context)


def listquizresults(request):
    """For superuser, provides a link to the result page for each quiz (checkresults)""" 
    # Only superusers can view quizresults
    if request.user.is_authenticated() and request.user.is_superuser:
        quizzes_list = Quiz.objects.all()
        context = {
            'quizzes_list': quizzes_list,
        }
        # This template will provide links to the checkresults page for each quiz
        return render(request, 'quizsite/listquizresults.html', context)


def checkresults(request, quiz_id):
    """For superuser and a given quiz, provides links to the result of each user who took quiz"""
    # Only superusers can view quizresults
    if request.user.is_authenticated() and request.user.is_superuser:
        quiz = get_object_or_404(Quiz, pk=quiz_id)
        quizresult_list = QuizResult.objects.filter(quiz=quiz, finished=True)
        user_list = User.objects.filter(id__in=quizresult_list.values('user_id'))
        context = {'quiz': quiz, 'user_list': user_list}
        # This page provides links to the result page for each user who finished the quiz.
        return render(request, 'quizsite/checkresults.html', context)
    else:
        context = {'error': "Only superusers can see quiz results."}
        return render(request, 'quizsite/error.html', context)


def quizresults(request, quiz_id, username):
    """If superuser, given a quiz and username, calculates and displays the total scoring of that quiz submission"""
    # Only superusers can view quizresults
    if request.user.is_authenticated() and request.user.is_superuser:
        quiz = get_object_or_404(Quiz, pk=quiz_id)
        user = get_object_or_404(User, username=username)
        if len(QuizResult.objects.filter(quiz=quiz, user=user)) == 1:
            if len(QuizResult.objects.filter(quiz=quiz, user=user, finished=True)) == 1:
                quizresult = get_object_or_404(QuizResult, quiz=quiz, user=user, finished=True)
                question_list = Question.objects.filter(quiz__id=quiz_id)
                # This is the first time that score is properly calculated, and set, in the QuizResult object.
                # The quiz is not scored until a superuser checks the results.
                score = 0
                for question in question_list:

quizsite/quizsite/templates/quizsite/addquestion.html
<!DOCTYPE html>

{% extends "base.html" %}
<html>
{% block content %}
    <head>
        <base href="{% url 'quizzes:addquestion' %}" />
        <title>"Add Quiz, Question, or Answer"</title>
    </head>
    <body>
        <p> Once you hit submit, if it redirects you to this page, then the quiz/question/answer
        has successfully been added to the database, and you can continue to add content. Otherwise, you 
        will see an error message! </p>
        <p> Add a new question to a quiz. Select the text and which quiz to add it to. </p>
        <form action="{% url 'quizzes:addquestion' %}" method="post">
            {% csrf_token %}
            <ol>
            {{ questionform.as_ul }}
            </ol>
            <input type="submit" value="Add Question" />
        </form>
        <p> Add a new answer. Add the text, the question it answers, and whether it is correct. </p>
        <form action="{% url 'quizzes:addanswer' %}" method="post">
            {% csrf_token %}
            <ol>
            {{ answerform.as_ul }}
            </ol>
            <input type="submit" value="Add Answer" />
        </form>
        <p> Create a new quiz. Select the name of the quiz and submit. </p>
        <form action="{% url 'quizzes:addquiz' %}" method="post">
            {% csrf_token %}
            <ol>
            {{ quizform.as_ul }}
            </ol>
            <input type="submit" value="Add Quiz" />
        </form>
    </body>
{% endblock %}
</html>

quizsite/quizsite/templates/quizsite/alreadybegunquiz.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
{% block content %}
<head>
<title>You have already begun this quiz.</title>
</head>
<body>

{{ error }}
<br>
<li><a href="{% url 'quizzes:question' quiz.id quiz.questions.all.0.id %}"> First question in Quiz: {{quiz}}</a></li>.

{% endblock %}
</html>

quizsite/quizsite/templates/quizsite/beginquiz.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
{% block content %}
<head>
<title>Begin Quiz: {{quiz}}</title>
</head>
<body>

{% if user.is_authenticated %}

<h1>Begin Quiz: {{quiz}}</h1>
<p> Click the button below to begin a quiz attempt. </p>
<form action="{% url 'quizzes:beginquiz' quiz.id %}" method="post">
    {% csrf_token %}
    <ol>
        {{ quizresultform }}
    </ol>
    <input type="submit" value="Begin Quiz" />
</form>

<br>
<p> Alternatively, if you would like to simply view the questions in the quiz, you can click on the link below </p> 
<li><a href="{% url 'quizzes:question' quiz.id quiz.questions.all.0.id %}"> Skip to the first question in Quiz: {{quiz}} without beginning the quiz attempt.</a></li>.

{% else %}
<p> You are not logged in, so you may not begin a quiz attempt. However, you can follow the link below to the first question in this quiz. </p> 
<li><a href="{% url 'quizzes:question' quiz.id quiz.questions.all.0.id %}"> Skip to the first question in Quiz: {{quiz}} without beginning the quiz attempt.</a></li>.

{% endif %}
</body>

{% endblock %}
</html>

quizsite/quizsite/templates/quizsite/bugreport.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
{% block content %}
    <head>
        <base href="{% url 'quizzes:bugreport' %}" />
        <title>"Submit Bug Report"</title>
    </head>
    <body>
        <form action="{% url 'quizzes:bugreport' %}" method="post">
            {% csrf_token %}
            <ol>
            {{ bugreportform }}
            </ol>
            <input type="submit" value="Submit Bug Report" />
        </form>
    </body>
{% endblock %}
</html>

quizsite/quizsite/templates/quizsite/checkresults.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
{% block content %}
<head>
<title>Find User Results for Quiz: {{quiz}} </title>
</head>
<body>

<h1> User Results for Quiz: {{quiz}}</h1>
<p></p>

{% if user_list %}
    <ul>
    {% for user in user_list %}
        <li><a href="{% url 'quizzes:quizresults' quiz.id user.username %}">Result for User: {{user.username}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No users have submitted this quiz.</p>
{% endif %}
</body>

{% endblock %}
</html>

quizsite/quizsite/templates/quizsite/endofquiz.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
{% block content %}
<head>
<title> End of Quiz: {{quiz} </title>
</head>
<body>

<p> You may now either submit this quiz (which will be final), or you may return to the first question in this quiz to change your previous answers </p>
<li> <a href="{% url 'quizzes:finishquiz' quiz.id %}">Submit the quiz: {{quiz}}</a> </li>
<br>
{% if first_question %}
<li><a href="{% url 'quizzes:question' quiz.id first_question.id %}"> Return to the first question in Quiz: {{quiz}}</a></li>
{% else %}
{% endif %}
</body>
{% endblock %}
</html>

quizsite/quizsite/templates/quizsite/error.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
{% block content %}
<head>
<title>The site has encountered an error.</title>
</head>
<body>

{{ error }}

{% endblock %}
</html>

quizsite/quizsite/templates/quizsite/home.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
{% block content %}
<head>
<title>Home</title>
</head>
<body>

<h1>Dylan O'Connell's Quizsite Homepage</h1>
<p>  </p>


      {% if not user.is_authenticated %}
      <p> You must be logged in before you can take a quiz. If you do not yet have an account, you can register below. </p>
      <li><a href="{% url 'django.contrib.auth.views.login' %}"> Login</a></li>
      <br>
      <li><a href="{% url 'account:register' %}"> Register an Account</a></li>
      <br>
      {% else %}
      <p> Welcome back, {{user}}. If you'd like to begin a new quiz, click "List of Quizzes" to select which quiz.  </p>
      <li><a href="{% url 'account:logout' %}"> Logout</a></li> <br>
      {% endif %}
      <li><a href="{% url 'quizzes:quizzes' %}"> List of Quizzes</a></li>
      <br>
      <li><a href="{% url 'quizzes:bugreport' %}"> Find an issue? Submit a bug report! </a></li>
      <br>
      {% if user.is_superuser %}
      <h2> Superuser Tools: </h2>
      <p> If you'd like to add a quiz or add content to an existing one, click on below.
      <li><a href="{% url 'quizzes:addquestion' %}"> Add a Quiz, Question, or Answer</a></li>
      <p> If you'd like to view the results of a quiz, click below to see a list of possible quizzes. </p>
      <li><a href="{% url 'quizzes:listquizresults' %}"> Check Quiz Results</a></li>
      <p> If you'd like to view a list of all submitted bug reports, then click below</p>
      <li><a href="{% url 'quizzes:viewbugreports' %}"> View Bug Reports</a></li>
      <br>
      {% else %}
      {% endif %}


</body>

{% endblock %}

</html>

quizsite/quizsite/templates/quizsite/listquizresults.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
{% block content %}
<head>
<title>Quiz Results</title>
</head>
<body>

<h1>List of Available Quiz Results</h1>
<p></p>

{% if quizzes_list %}
    <ul>
    {% for quiz in quizzes_list %}
        {% if quiz.questions.all %}
            <li><a href="{% url 'quizzes:checkresults' quiz.id %}">{{ quiz }}</a></li>
        {% else %}
            <li>{{quiz}}</li>
        {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p>No quizzes here.</p>
{% endif %}
</body>

{% endblock %}
</html>

quizsite/quizsite/templates/quizsite/question.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
{% block content %}
<head>
<title> {{quiz}} </title>
</head>
<body>

<h1>Question #{{curr_question_number}}:</h1>
<legend> {{question.text}} </legend>
<br>
<form method="post" action="{% url 'quizzes:submitanswer' quiz.id question.id %}">
{% csrf_token %}
{{ formset.management_form }}
<table border="1">
    <tr>
        {% for item in formset_answers %}
            <td> {{ item.1.text }} </td>
            {{ item.0 }}
        {% endfor %}
    </tr>
</table>
    <input type="submit" value="Submit Answer" />
</form>
<br>

<p>
{% if prev_question %}
    <li><a href="{% url 'quizzes:question' quiz.id prev_question.id %}">Previous: Question {{ prev_question_number}}</a></li>
{% else %}
    <li> First question in the quiz. </li>
{% endif %}
<br>
{% if next_question %}
    <li><a href="{% url 'quizzes:question' quiz.id next_question.id %}">Next: Question {{ next_question_number}}</a></li>
{% else %}
<li> Final question in the quiz. </li> <br>
<!--  <a href="{% url 'quizzes:finishquiz' quiz.id %}">Submit the quiz: {{quiz}}</a> -->
{% endif %}
</p>
</body>
{% endblock %}
</html>

quizsite/quizsite/templates/quizsite/quizresults.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
{% block content %}
<head>
<title> {{this_user}}'s results for {{quiz}} </title>
</head>
<body>

<h1>{{this_user}}'s results for {{quiz}}</h1>
{% for question_answers in answer_lists %}
    <table border = "1">
        {{question_answers.0.text}}
            <th>Answer: </th>
            <th>User Selected: </th>
            <th>Correctness: </th>
        {% for answer_result in question_answers.1 %}
            <tr>
            <td>{{answer_result.0.text}}</td>
            <td>{{answer_result.1.selected}}</td>
            <td>{{answer_result.0.get_correct_type_display}}</td>
            </tr>
        {% endfor %}
    </table>
    <br>
{% endfor %}
<p>
FINAL SCORE: {{score}}
</p>
</body>
{% endblock %}
</html>

quizsite/quizsite/templates/quizsite/quizzes.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
{% block content %}
<head>
<title>Quizzes</title>
</head>
<body>

<h1>List of Available Quizzes</h1>
<p> If you click on a link below, you will be taken to that quiz's page to begin a quiz attempt.</p>

{% if quizzes_list %}
    <ul>
    {% for quiz in quizzes_list %}
        {% if quiz.questions.all %}
            <li><a href="{% url 'quizzes:beginquiz' quiz.id %}">{{ quiz }}</a></li>
        {% else %}
            <li>{{quiz}}</li>
        {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p>No quizzes here.</p>
{% endif %}
</body>

{% endblock %}
</html>

quizsite/quizsite/templates/quizsite/submittedquiz.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
{% block content %}
<head>
<title> Quiz: {{quiz}} successfully submitted </title>
</head>
<body>

<p> Congratulations! You have successfully submitted your answers for Quiz: {{quiz}}. For security reasons, you cannot personally view the scoring of your quiz, as other students may not have taken it yet. The administrator will contact you with your full score report when they are ready. </p>
<br>
</body>
{% endblock %}
</html>

quizsite/quizsite/templates/quizsite/viewbugreports.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
{% block content %}
<head>
<title> Bug reports </title>
</head>
<body>

<h1>Bug Reports</h1>
<table border = "1">
{% for bugreport in bugreport_list %}
            <th>User: </th>
            <th>Time Stamp: </th>
            <th>Bug Report: </th>
            <tr>
            <td>{{bugreport.user}}</td>
            <td>{{bugreport.timestamp}}</td>
            <td>{{bugreport.report}}</td>
            </tr>
    <br>
{% endfor %}
</table>
</body>
{% endblock %}
</html>